#!/bin/bash

[[ -z ${1+x} ]] || [[ "$@" =~ '-h' ]] || [[ "$@" =~ '--help' ]] && {
    echo "Turn a markdown into a slide

Usage:

$0 <presentation.md> [output.html] [options]

-h to get this help
--help to get this help

Where options may be:
--open-in-browser

    "
    exit 0
}

input_file="$(realpath $1)"

[[ ! -z $2 ]] && output_file="$(realpath $2)"

[[ -z $output_file ]] && output_file="$(echo $input_file | rev | cut -d "."  -f1 --complement | rev ).html"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR;

pandoc --standalone --from markdown --to html5 \
	--template $SCRIPT_DIR/template.html --self-contained \
	"$input_file" | sed 's|<hr.*/>|</section>\n    <section>|' > $output_file


[[ "$@" =~ "--open-in-browser" ]] && {
    $BROWSER $output_file
}
